services:
  app-a:
    # build: ./fastapi_app/
    container_name: app-a
    image: ghcr.io/blueswen/fastapi-jaeger/app:latest
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
    environment:
      MODE: "otlp-grpc"
      OTEL_SERVICE_NAME: "app-a"
      OTLP_GRPC_ENDPOINT: "otel-collector:4317"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"
  
  app-b:
    # build: ./fastapi_app/
    container_name: app-b
    image: ghcr.io/blueswen/fastapi-jaeger/app:latest
    ports:
      - "8001:8000"
    volumes:
      - ./fastapi_app:/app
    environment:
      MODE: "otlp-http"
      OTEL_SERVICE_NAME: "app-b"
      OTLP_HTTP_ENDPOINT: "http://otel-collector:4318/v1/traces"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"
  
  app-c:
    # build: ./fastapi_app/
    container_name: app-c
    image: ghcr.io/blueswen/fastapi-jaeger/app:latest
    ports:
      - "8002:8000"
    volumes:
      - ./fastapi_app:/app
    environment:
      MODE: "otlp-grpc"
      OTEL_SERVICE_NAME: "app-c"
      OTLP_GRPC_ENDPOINT: "jaeger-collector:4317"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"

  app-d:
    container_name: app-d
    build: ./fastapi_app/
    ports:
      - "8003:8000"
    volumes:
      - ./fastapi_app:/app
    environment:
      MODE: "otlp-http"
      OTEL_SERVICE_NAME: "app-d"
      OTLP_HTTP_ENDPOINT: "http://jaeger-collector:4318/v1/traces"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"

  jaeger-collector:
    container_name: jaeger-collector
    image: jaegertracing/jaeger-collector:1.57.0
    command: 
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--collector.otlp.enabled=true"
    environment: 
      - SAMPLING_CONFIG_TYPE=adaptive
    ports:
      - "4317" # accept OpenTelemetry Protocol (OTLP) over gRPC
      - "4318" # accept OpenTelemetry Protocol (OTLP) over HTTP
    restart: on-failure
    depends_on:
      - cassandra-schema

  cassandra:
    container_name: cassandra
    image: cassandra:4.1.4

  cassandra-schema:
    container_name: cassandra-schema
    image: jaegertracing/jaeger-cassandra-schema:1.57.0
    depends_on:
      - cassandra

  jaeger-query:
    container_name: jaeger-query
    image: jaegertracing/jaeger-query:1.57.0
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
    ports:
      - "16686:16686"
      - "16687:16687"
    restart: on-failure
    depends_on:
      - cassandra-schema

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.100.0
    command:
      - "--config=/conf/config.yaml"
    volumes:
      - ./etc/otel-collector-config.yaml:/conf/config.yaml
    ports:
      - "4317" # OTLP gRPC receiver
      - "4318" # OTLP http receiver
    restart: on-failure
    depends_on:
      - jaeger-collector
